### ISSUE TITLE
Improve initSettingForAuto.py

### ISSUE THREAD

**Issue by QimatLuo** [exosite/dqa-exosense-data#11]
https://github.com/exosite/dqa-exosense-data/blob/379c537dd60ef2c95471b157f261c6d6548dd60f/createScript/initSettingForAuto.py#L27
If everyone runs the script will get failed due to the conflict issue.

I think the easy way is to separate the create roles to another file to run it when you need it.
 
Or try to make the code to not break in this case.

**Comment by CometLin** [comment]
Create script update to another file to resolve the conflict
